import Head from 'next/head'

import ScatterChart from '../components/ScatterChart'

const data = [
  {
    x: -13,
    y: 23,
  },
]

export default function Home() {
  return (
    <div>
      <Head>
        <title>El Mayo&apos;s Next.js + Tailwind starter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <ScatterChart dataPoints={data} />
      </main>
    </div>
  )
}
