import Head from 'next/head'
import { useState } from 'react'

import QuestionnaireForm from '../components/QuestionnaireForm'
import { questionnaire } from '../data'
import { Questionnaire } from '../types'

type Props = {
  questionnaire: Questionnaire
}

export default function MDBA({ questionnaire }: Props) {
  console.log(`questionnaire`, questionnaire)
  const [isFormSubmitted, setIsFormSubmitted] = useState(false)

  return (
    <div className="p-4">
      <Head>
        <title>El Mayo&apos;s Next.js + Tailwind starter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="max-w-6xl mx-auto">
        <h1 className="text-center text-4xl font-bold text-purple-700 pt-10">
          Verhaltensanalyse
        </h1>
        {isFormSubmitted ? (
          <div>
            <div>Result</div>
            <button onClick={() => setIsFormSubmitted(false)}>Try Again</button>
          </div>
        ) : (
          <>
            <div className="py-10 max-w-xs md:max-w-2xl mx-auto space-y-2">
              <p>
                {' '}
                Im folgenden Fragebogen sollst du angeben, wie du dich
                normalerweise in Alltagssituationen verhältst. Aus der
                Auswertung ergibt sich ein klares Bild wie du dich selbst
                siehst.
              </p>
              <p>
                Bewerte jedes Paar der Aussagen A und B mit insgesamt drei
                Punkten, je nachdem, wie zutreffend die Aussage ist. Auch wenn
                du glaubst, dass manche Aussagenpaare gleichermassen zutreffen,
                solltest du der Alternative mehr Punkte geben, die für dein
                Verhalten typischer ist.
              </p>
            </div>
            <QuestionnaireForm
              questionnaire={questionnaire}
              setIsFormSubmitted={setIsFormSubmitted}
            />
          </>
        )}
      </main>
    </div>
  )
}

export async function getStaticProps() {
  return { props: { questionnaire } }
}
