import Head from 'next/head'

import { questionnaire } from '../data'
import { Questionnaire } from '../types'

type Props = {
  questionnaire: Questionnaire
}

export default function MDBA({ questionnaire }: Props) {
  console.log(`questionnaire`, questionnaire)
  return (
    <div>
      <Head>
        <title>El Mayo&apos;s Next.js + Tailwind starter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
          Data:
          {questionnaire.map((questionSet) => {
            return (
              <div key={questionSet.set}>
                {questionSet.choices.map((choice) => {
                  return (
                    <div key={choice.choice}>
                      {`${questionSet.set}${choice.choice}`} {choice.statement}
                    </div>
                  )
                })}
              </div>
            )
          })}
        </div>
      </main>
    </div>
  )
}

export async function getStaticProps() {
  return { props: { questionnaire } }
}
