import Head from 'next/head'

import BehaviourTypeTable from '../components/BehaviourTypeTable'

export default function Home() {
  return (
    <div className="p-4">
      <Head>
        <title>El Mayo&apos;s MDBA Analyse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="max-w-6xl mx-auto">
        <BehaviourTypeTable />
      </main>
    </div>
  )
}
